apiVersion: apps/v1
kind: Deployment
metadata:
  name: paint-backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: paint-backend
  template:
    metadata:
      labels:
        app: paint-backend
    spec:
      containers:
      - name: backend
        image: paint-backend:1.1
        env:
        - name: REDIS_HOST
          value: redis
        - name: PORT
          value: "3000"
        - name: DATABASE_URL
          value: "postgresql://postgres:postgres@postgres:5432/canvas_db"
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: paint-backend
spec:
  type: ClusterIP
  selector:
    app: paint-backend
  ports:
  - port: 3000
