apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: paint-ingress
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: paint.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: paint-frontend
            port:
              number: 80
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: paint-backend
            port:
              number: 3000
      - path: /socket.io
        pathType: Prefix
        backend:
          service:
            name: paint-backend
            port:
              number: 3000
